package jobengine

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sync"
	"testing"

	"github.com/google/uuid"
	"github.com/rgarcia2304/flight-circle-search/internal/geo"
	"github.com/rgarcia2304/flight-circle-search/internal/routes"
)

// --- mocks ---

type mockRepo struct {
	mu         sync.Mutex
	createdJob *SearchJob
	created    []SearchJobResult
	pending    map[uuid.UUID][]SearchJobResult
}

func (m *mockRepo) CreateJob(_ context.Context, job SearchJob, pairs []SearchJobResult) (uuid.UUID, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if job.ID == uuid.Nil {
		job.ID = uuid.New()
	}
	m.createdJob = &job
	m.created = pairs
	if m.pending == nil {
		m.pending = make(map[uuid.UUID][]SearchJobResult)
	}
	m.pending[job.ID] = pairs
	// Assign IDs as if generated by DB.
	for i := range pairs {
		pairs[i].ID = int64(i + 1)
		pairs[i].JobID = job.ID
	}
	return job.ID, nil
}

func (m *mockRepo) GetJob(_ context.Context, id uuid.UUID) (SearchJob, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.createdJob == nil || m.createdJob.ID != id {
		return SearchJob{}, ErrJobNotFound
	}
	return *m.createdJob, nil
}

func (m *mockRepo) ListResults(_ context.Context, _ uuid.UUID) ([]SearchJobResult, error) {
	return nil, nil
}

func (m *mockRepo) GetPendingResults(_ context.Context, jobID uuid.UUID) ([]SearchJobResult, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.pending[jobID], nil
}

func (m *mockRepo) ClaimNextResult(_ context.Context, _ uuid.UUID) (*SearchJobResult, error) {
	return nil, nil
}

func (m *mockRepo) UpdateResult(_ context.Context, _ int64, _ string, _ json.RawMessage, _ *string) error {
	return nil
}

func (m *mockRepo) MarkResultDeadLetter(_ context.Context, _ int64, _ string) error {
	return nil
}

func (m *mockRepo) UpdateJobProgress(_ context.Context, _ uuid.UUID) error { return nil }

func (m *mockRepo) MarkJobStatus(_ context.Context, _ uuid.UUID, _ JobStatus, _ *string) error {
	return nil
}

func (m *mockRepo) MarkJobCompleteIfDone(_ context.Context, _ uuid.UUID) (bool, error) {
	return false, nil
}

// --- airport source ---

type mockAirports struct {
	airports []geo.Airport
	graph    routes.RouteGraph
}

func (m *mockAirports) Airports(_ context.Context) ([]geo.Airport, error) {
	return m.airports, nil
}

func (m *mockAirports) RouteGraph(_ context.Context) (routes.RouteGraph, error) {
	return m.graph, nil
}

// --- enqueuer ---

type mockEnqueuer struct {
	mu    sync.Mutex
	items []SearchJobResult
	err   error
}

func (m *mockEnqueuer) EnqueueBatch(_ context.Context, results []SearchJobResult) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.err != nil {
		return m.err
	}
	m.items = append(m.items, results...)
	return nil
}

// --- tests ---

func newTestAirports() []geo.Airport {
	// NYC area, Berlin area + nearby.
	return []geo.Airport{
		{IATA: "JFK", Name: "JFK", Location: geo.Point{Lat: 40.6398, Lng: -73.7789}},
		{IATA: "EWR", Name: "EWR", Location: geo.Point{Lat: 40.6925, Lng: -74.1687}},
		{IATA: "TXL", Name: "TXL", Location: geo.Point{Lat: 52.5597, Lng: 13.2877}},
		{IATA: "PRG", Name: "PRG", Location: geo.Point{Lat: 50.1008, Lng: 14.26}},
	}
}

func newTestGraph() routes.RouteGraph {
	g := routes.RouteGraph{
		"JFK": {"TXL": {}, "PRG": {}},
		"EWR": {"TXL": {}, "PRG": {}},
		"TXL": {"JFK": {}, "EWR": {}},
		"PRG": {"JFK": {}, "EWR": {}},
	}
	return g
}

func validRequest() SearchRequest {
	return SearchRequest{
		OriginLat:  40.6398,
		OriginLng:  -73.7789,
		OriginR:    100,
		DestLat:    52.36,
		DestLng:    13.50,
		DestR:      350,
		DepartFrom: "2026-10-15",
		DepartTo:   "2026-10-17",
	}
}

func TestService_GenerateTuples_FullCombinatorics(t *testing.T) {
	repo := &mockRepo{}
	enq := &mockEnqueuer{}
	svc := NewService(repo, &mockAirports{airports: newTestAirports(), graph: newTestGraph()}, enq)

	id, total, err := svc.Submit(context.Background(), validRequest())
	if err != nil {
		t.Fatalf("submit: %v", err)
	}
	if id == uuid.Nil {
		t.Fatal("expected non-nil id")
	}
	// 2 origins (JFK, EWR) x 2 destinations (BER, PRG) x 3 dates = 12
	if total != 12 {
		t.Errorf("total = %d, want 12 (2 origins x 2 dests x 3 dates)", total)
	}
	if len(enq.items) != 12 {
		t.Errorf("enqueued %d, want 12", len(enq.items))
	}
}

func TestService_TooManyPairsRejected(t *testing.T) {
	repo := &mockRepo{}
	enq := &mockEnqueuer{}
	svc := NewService(repo, &mockAirports{airports: newTestAirports(), graph: newTestGraph()}, enq)

	// Use a small max-pairs cap to force rejection.
	svc.maxPairs = 5

	_, total, err := svc.Submit(context.Background(), validRequest())
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !errors.Is(err, ErrTooManyPairs) {
		t.Errorf("err = %v, want ErrTooManyPairs", err)
	}
	if total != 12 {
		t.Errorf("total = %d, want 12 (count should still be reported)", total)
	}
}

func TestService_InvalidInputRejected(t *testing.T) {
	repo := &mockRepo{}
	enq := &mockEnqueuer{}
	svc := NewService(repo, &mockAirports{airports: newTestAirports(), graph: newTestGraph()}, enq)

	bad := validRequest()
	bad.OriginLat = 999 // out of range
	_, _, err := svc.Submit(context.Background(), bad)
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !errors.Is(err, ErrInvalidInput) {
		t.Errorf("err = %v, want ErrInvalidInput", err)
	}
}

func TestService_BadDateFormatRejected(t *testing.T) {
	repo := &mockRepo{}
	enq := &mockEnqueuer{}
	svc := NewService(repo, &mockAirports{airports: newTestAirports(), graph: newTestGraph()}, enq)

	bad := validRequest()
	bad.DepartFrom = "2026/10/15"
	_, _, err := svc.Submit(context.Background(), bad)
	if err == nil {
		t.Fatal("expected error, got nil")
	}
}

func TestService_InvertedDateRangeRejected(t *testing.T) {
	repo := &mockRepo{}
	enq := &mockEnqueuer{}
	svc := NewService(repo, &mockAirports{airports: newTestAirports(), graph: newTestGraph()}, enq)

	bad := validRequest()
	bad.DepartFrom = "2026-10-17"
	bad.DepartTo = "2026-10-15"
	_, _, err := svc.Submit(context.Background(), bad)
	if err == nil {
		t.Fatal("expected error, got nil")
	}
}

func TestService_SameDayGeneratesOnePairPerAirport(t *testing.T) {
	repo := &mockRepo{}
	enq := &mockEnqueuer{}
	svc := NewService(repo, &mockAirports{airports: newTestAirports(), graph: newTestGraph()}, enq)

	req := validRequest()
	req.DepartFrom = "2026-10-15"
	req.DepartTo = "2026-10-15"

	_, total, err := svc.Submit(context.Background(), req)
	if err != nil {
		t.Fatalf("submit: %v", err)
	}
	if total != 4 {
		t.Errorf("total = %d, want 4 (2x2 with 1 date)", total)
	}
}

func TestService_OriginAndDestOverlap(t *testing.T) {
	// When origin and dest circles overlap, the route graph still filters correctly.
	repo := &mockRepo{}
	enq := &mockEnqueuer{}
	airports := []geo.Airport{
		{IATA: "AAA", Name: "AAA", Location: geo.Point{Lat: 0, Lng: 0}},
		{IATA: "BBB", Name: "BBB", Location: geo.Point{Lat: 1, Lng: 1}},
	}
	graph := routes.RouteGraph{
		"AAA": {"BBB": {}},
		"BBB": {"AAA": {}},
	}
	svc := NewService(repo, &mockAirports{airports: airports, graph: graph}, enq)

	req := SearchRequest{
		OriginLat: 0, OriginLng: 0, OriginR: 200,
		DestLat: 0, DestLng: 0, DestR: 200,
		DepartFrom: "2026-10-15", DepartTo: "2026-10-15",
	}
	_, total, err := svc.Submit(context.Background(), req)
	if err != nil {
		t.Fatalf("submit: %v", err)
	}
	// Self-pairs (AAA, AAA) and (BBB, BBB) are excluded by GenerateAllPairs.
	if total != 2 {
		t.Errorf("total = %d, want 2 (AAA<->BBB both directions)", total)
	}
}

func TestValidateRequest(t *testing.T) {
	tests := []struct {
		name string
		req  SearchRequest
		want error
	}{
		{
			name: "valid",
			req:  validRequest(),
			want: nil,
		},
		{
			name: "origin lat out of range",
			req:  func() SearchRequest { r := validRequest(); r.OriginLat = 91; return r }(),
			want: ErrInvalidInput,
		},
		{
			name: "negative origin radius",
			req:  func() SearchRequest { r := validRequest(); r.OriginR = -1; return r }(),
			want: ErrInvalidInput,
		},
		{
			name: "destination radius too large",
			req:  func() SearchRequest { r := validRequest(); r.DestR = 99999; return r }(),
			want: ErrInvalidInput,
		},
		{
			name: "bad date format",
			req:  func() SearchRequest { r := validRequest(); r.DepartFrom = "10-15-2026"; return r }(),
			want: ErrInvalidInput,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := validateRequest(tt.req)
			if tt.want == nil && err != nil {
				t.Errorf("err = %v, want nil", err)
			} else if tt.want != nil && !errors.Is(err, tt.want) {
				t.Errorf("err = %v, want %v", err, tt.want)
			}
		})
	}
}

// ensure unused imports are detected
var (
	_ = fmt.Sprintf
	_ geo.Point
	_ routes.RouteGraph
)
